### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms-cloud#42]
**Describe the bug**
Error running project in container
```
(base) kye@api:~/swarms-cloud$ docker run --gpus all -p 8000:8000 newcogvlm
/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
A new version of the following files was downloaded from https://huggingface.co/THUDM/cogvlm-chat-hf:
- configuration_cogvlm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/THUDM/cogvlm-chat-hf:
- visual.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/THUDM/cogvlm-chat-hf:
- modeling_cogvlm.py
- visual.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
========Use torch type as:torch.bfloat16 with device:cuda========


Downloading shards: 100%|██████████| 8/8 [05:07<00:00, 38.50s/it]
Loading checkpoint shards: 100%|██████████| 8/8 [00:05<00:00,  1.42it/s]
INFO:     Started server process [1]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
TypeError: 'coroutine' object is not an async iterator

/usr/local/lib/python3.10/dist-packages/uvicorn/lifespan/on.py:91: RuntimeWarning: coroutine 'lifespan' was never awaited
  return
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
ERROR:    Application startup failed. Exiting.

the whole message i even set all gpus```

**Comment by evelynmitchell** [comment]
Closing, this was a long time ago.
